
GET https://{{host}}/service/action/{{projectId}}/rbs.rule.get.EXECUTE?auth={{accessToken}}&data=ewogICAgIm9wdGlvbklkIjogIlJFVFVSTl9JVEVNUyIsCiAgICAiZGF0YSI6IFsKICAgICAgICB7CiAgICAgICAgICAgICJtZXJjaGFudElkIjogImRlZmF1bHQiLAogICAgICAgICAgICAidmFyaWFudEdyb3VwSWQiOiAiRCIsCiAgICAgICAgICAgICJpdGVtSWQiOiAiNzY4NSIsCiAgICAgICAgICAgICJhbW91bnQiOiAyMDAwMCwKICAgICAgICAgICAgImlkIjogIjIiLAogICAgICAgICAgICAic3RvcmVJZCI6ICJTVE9SRV9BIiwKICAgICAgICAgICAgInN0YXR1cyI6ICIxMCIKICAgICAgICB9CiAgICBdCn0%3D HTTP/1.1
Content-Type: application/json
