
GET https://{{host}}/service/action/{{projectId}}/rbs.rule.get.EXECUTE?auth={{accessToken}}&data=eyAib3B0aW9uSWQiOiAiUkVUVVJOX0lURU1TIiwgImRhdGEiOiB7ICJ0ZXN0IjogInRlc3QiIH0gfQ%3D%3D HTTP/1.1
Content-Type: application/json
