
# @name validateCode
POST /user/action?auth={{accessToken}}&action=rbs.basicauth.request.ANSWER_CHALLENGE HTTP/1.1
Host: {{host}}

{
    "hashedKey": "aEWcm681k0BK57fCtRr2T/uQXUPpmM9pTlJeTdsf3cQ=",    
    "answer": {
        "code": "141414"
    }
}

###

# @name signup
POST /user/action?auth={{accessToken}}&action=rbs.basicauth.request.ANSWER_CHALLENGE HTTP/1.1
Host: {{host}}

{
    "hashedKey": "aEWcm681k0BK57fCtRr2T/uQXUPpmM9pTlJeTdsf3cQ=",    
    "answer": {
        "firstName": "Baran",
        "lastName": "Baygan",
        "email": "baran@rettermobile.com",
        "phoneNumber": "+905309364921",
        "birthDate": "05/06/1980",
        "acceptedKvkk": true,
        "acceptedTerms": true
    }
}