
# @name getAnonymToken
GET https://{{host}}/public/anonymous-auth?projectId={{projectId}} HTTP/1.1




###

@anonymAccessToken = {{getAnonymToken.response.body.$.accessToken}}


# @name start
POST https://{{host}}/user/action/{{projectId}}/rbs.basicauth.request.START_AUTH?auth={{anonymAccessToken}} HTTP/1.1

{
    "msisdn": "+905309364916"
}


###

# @name validateCode
POST https://{{host}}/user/action/{{projectId}}/rbs.basicauth.request.ANSWER_CHALLENGE?auth={{anonymAccessToken}} HTTP/1.1

{
    "hashedKey": "RG0ZEVhVwqEesTQ3uJHodYJj9I2JencOGzSNlqeqpdc=",
    "answer": {
        "code": "1414"
    }
}

###

# @name signup  
POST https://{{host}}/user/action/{{projectId}}/rbs.basicauth.request.ANSWER_CHALLENGE?auth={{anonymAccessToken}} HTTP/1.1

{
    "hashedKey": "RG0ZEVhVwqEesTQ3uJHodYJj9I2JencOGzSNlqeqpdc=",
    "answer": {
        "firstName": "Baran",
        "lastName": "Baygan",
        "email": "baran@rettermobile.com",
        "phoneNumber": "+905309364916",
        "birthDate": "05/06/1980",
        "acceptedKvkk": true,
        "acceptedTerms": true
    }
}

###

@customToken = {{validateCode.response.body.$[0].response.customToken}}

GET https://{{host}}/public/auth?customToken={{customToken}} HTTP/1.1

