###
# @name getUserProfile
POST https://{{host}}/user/action/{{projectId}}/rbs.profile.request.DATA?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
  "userId": "1232k12r124123123dapwoq"
}

###
# @name getUserProfile
POST https://{{host}}/user/action/{{projectId}}/rbs.profile.request.DATA?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
  "phoneNumber": "905555555555"
}
