###
# @name updateProfile
POST https://{{host}}/user/action/{{projectId}}/rbs.profile.request.UPDATE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "Baran",
    "lastName": "Baygan",
    "birthDate": "05/06/1980",
    "email": "baran@rettermobile.com",
    "receivePromotionalContent": true
}