
# Aggregate with filters
GET https://{{host}}/user/action/{{projectId}}/rbs.catalog.get.AGGREGATE?auth={{accessToken}}&data=ewogICAgIm1vZGVsTmFtZSI6ICJyYnMucGltcHJvZHVjdCIsCiAgICAiZmlsdGVycyI6IFsKICAgICAgIHsKICAgICAgICAgICAiZmlsdGVySWQiOiAiY2F0ZWdvcmllcyIsCiAgICAgICAgICAgImZpbHRlclZhbHVlcyI6IFsiaGFyZGFsIl0KICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICJmaWx0ZXJJZCI6ICJzaXplIiwKICAgICAgICAgICAiZmlsdGVyVmFsdWVzIjogWyIxIEtHIl0KICAgICAgIH0KICAgIF0KfQ== HTTP/1.1
Content-Type: application/json

###
{
    "modelName": "rbs.pimproduct",
    "filters": [
       {
           "filterId": "categories",
           "filterValues": ["hardal"]
       },
        {
           "filterId": "size",
           "filterValues": ["1 KG"]
       }
    ]
}

ewogICAgIm1vZGVsTmFtZSI6ICJyYnMucGltcHJvZHVjdCIsCiAgICAiZmlsdGVycyI6IFsKICAgICAgIHsKICAgICAgICAgICAiZmlsdGVySWQiOiAiY2F0ZWdvcmllcyIsCiAgICAgICAgICAgImZpbHRlclZhbHVlcyI6IFsiaGFyZGFsIl0KICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICJmaWx0ZXJJZCI6ICJzaXplIiwKICAgICAgICAgICAiZmlsdGVyVmFsdWVzIjogWyIxIEtHIl0KICAgICAgIH0KICAgIF0KfQ==