POST /user/action?auth={{accessToken}}&action=rbs.wms.request.INCREASE_STOCK HTTP/1.1
Host: {{host}}

{
    "type": "SELLABLE",
    "merchantId": "DEFAULT",
    "storeId": "STORE_A",
    "variantGroupId": "NIKE_AIR",
    "sku": "NIKE_AIR_38_WHITE",
    "qty": 4
}