POST https://{{host}}/user/action/{{projectId}}/rbs.wms.request.UPDATE_STOCK?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "type": "SELLABLE",
    "merchantId": "default",
    "storeId": "STORE_A",
    "variantGroupId": "D",
    "sku": "7685",
    "qty": 4
}