POST /user/action?auth={{accessToken}}&action=rbs.wms.request.LIST_STOCKS HTTP/1.1
Host: {{host}}

[
    {
        "type": "$active",
        "merchantId": "default",
        "variantGroupId": "D",
        "sku": "7685"
    }
]