POST https://{{host}}/user/action/{{projectId}}/rbs.wms.request.LIST_STOCKS?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

[
    {
        "type": "$active",
        "merchantId": "AliMerchant",
        "variantGroupId": "AliVaraiantGroupId",
        "itemId": "AliItemId"
    }
]