POST /user/action?auth={{accessToken}}&action=rbs.wms.request.MOVE_STOCK HTTP/1.1
Host: {{host}}

{
    "from": "SELLABLE",
    "type": "RESERVED",
    "merchantId": "DEFAULT",
    "storeId": "STOREA",
    "variantGroupId": "NIKE_AIR",
    "sku": "NIKE_AIR_38_WHITE",
    "ownerId": "ORDERID",
    "exp": "20211227",
    "sectionId": "A13",
    "qty": 1,
    "actor": "test-actor"
}