POST /user/action?auth={{accessToken}}&action=rbs.wms.request.RESERVE_STOCK HTTP/1.1
Host: {{host}}

{
    "items": [
        {
            "merchantId": "default",
            "storeId": "STORE_A",
            "variantGroupId": "D",
            "itemId": "7685",
            "ownerId": "ORDER_ID_X",
            "qty": 1
        }
    ]
}