POST https://{{host}}/user/action/{{projectId}}/rbs.wms.request.RESTORE_STOCK?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "items": [
        {
            "merchantId": "default",
            "storeId": "STORE_A",
            "variantGroupId": "D",
            "itemId": "7685",
            "ownerId": "ORDER_ID_X",
            "qty": 1
        }
    ]
}