POST /user/action?auth={{accessToken}}&action=rbs.wms.request.UPSERT_OPTION HTTP/1.1
Host: {{host}}

{
    "first": "MAIN",
    "data": {
        "first": "SELLABLE",
        "active": "SELLABLE",
        "hold": "RESERVED",
        "last": "SOLD"
    }
}