POST https://{{host}}/user/action/{{projectId}}/rbs.wms.request.UPSERT_DIAGRAM?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "assets": [
        {
            "id": "SELLABLE",
            "name": "Sellable Products"
        },
        {
            "id": "RESERVED",
            "name": "Reserved Products"
        },
        {
            "id": "SOLD",
            "name": "Sold Products"
        },
        {
            "id": "INVEST",
            "name": "Investigation",
            "options": {
                "ttl": {
                    "val": 864000,
                    "to": "$back"
                }
            }
        },
        {
            "id": "DISCARD",
            "name": "Discarded Products"
        }
    ],
    "rules": [
        { "direction": ["SELLABLE", "INVEST"], "options": {} },
        {
            "direction": ["SELLABLE", "RESERVED"],
            "options": {
                "ttl": {
                    "val": 300,
                    "to": "SELLABLE"
                }
            }
        },

        { "direction": ["RESERVED", "SOLD"], "options": {} },
        { "direction": ["RESERVED", "SELLABLE"], "options": {} },
        { "direction": ["SOLD", "INVEST"], "options": {} },
        { "direction": ["INVEST", "DISCARD"], "options": {} },
        { "direction": ["INVEST", "SELLABLE"], "options": {} }
    ]
}