
POST https://{{host}}/user/action/{{projectId}}/rbs.businessuserauth.request.ADMIN_UPSERT_USER?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
  "email": "email@mail.com",
  "password": "password",
  "role": ["admin","user"],
  "name": "username",
  "claims": { "key": "value" }
}