
# @name getAnonymToken
GET /public/anonymous-auth?projectId={{projectId}} HTTP/1.1
Host: {{host}}

###

@anonymAccessToken = {{getAnonymToken.response.body.$.accessToken}}

# @name adminLogin
POST /user/action?auth={{anonymAccessToken}}&action=rbs.businessuserauth.request.LOGIN
Host: {{host}}

{
    "email": "root",
    "password": "12345"
}

###

@customToken = {{adminLogin.response.body.$[0].response.customToken}}

GET /public/auth?customToken={{customToken}} HTTP/1.1
Host: {{host}}
