POST https://{{host}}/user/action/{{projectId}}/rbs.notification.request.GET?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "userId": "rbsUserId",
    "notificationId": "82191b74-fea2-48a1-baaf-92abf8d40631"
}