POST https://{{host}}/user/action?auth={{accessToken}}&action=rbs.order.request.CAN_CREATE HTTP/1.1
Content-Type: application/json

[
    {
        "serviceId": "rbs.crm",
        "config": {
            "userId": "1063e61a-39cc-46a0-9bb7-b3dcee9df165"
        }
    },
    {
        "serviceId": "rbs.cart",
        "config": {
            "cartId": "7542e4c0ab",
            "totalAmount": 20000,
            "items": [
                {
                    "merchantId": "default",
                    "variantGroupId": "D",
                    "itemId": "7685",
                    "amount": 20000,
                    "qty": 1
                }
            ]
        }
    },
    {
        "serviceId": "rbs.billing",
        "config": {
            "paymentMethod": "masterpass"
        }
    },
    {
        "serviceId": "rbs.logistics",
        "config": {
            "addressId": "01EVTG8MJD1SJK0HRJXFCH4RKW",
            "zoneId": "ZONE_A",
            "pools": {
                "type": "CARGO",
                "provider": "ARAS_KARGO",
                "storeId": "STORE_A",
                "fee": 9
            }
        }
    }
]