POST https://{{host}}/user/action/{{projectId}}/rbs.oms.request.UPSERT_OPTION?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "optionId": "PRE_ORDER_CFG",
    "data": [
        {
            "phaseId": "RESERVE-STOCKS",
            "service": "rbs.wms",
            "required": true,
            "config": {}
        },
        {
            "phaseId": "PAYMENT",
            "service": "rbs.billing",
            "required": true,
            "config": {}
        },
        {
            "phaseId": "COMMIT-STOCKS",
            "service": "rbs.wms",
            "required": true,
            "config": {}
        }
    ]
}