# @name createPromotion

POST {{host}}/user/action/{{projectId}}/rbs.promotion.request.CREATE?auth={{accessToken}} HTTP/1.1

{
        "categoryId": "1",
        "applyOnce": false,
        "discardMinCartTotal": false,
        "dontCombineOtherPromotions": false,
        "maxAmount": 10000,
        "totalCount": 1000,
        "perUserCount": 5,
        "condition": {
            "minAmount": 20
        },
        "gifts": [
            {
                "giftType":"percentDiscount",
                "discount":50
            }
        ],
        "isVisible": true
}
###
@promotionId = {{createPromotion.response.body.$[0].response.promotionId}}

POST {{host}}/user/action/{{projectId}}/rbs.promotion.request.GET?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "promotionId": "{{promotionId}}"
}
###

POST {{host}}/user/action/{{projectId}}/rbs.promotion.request.DELETE?auth={{accessToken}} HTTP/1.1

{
    "promotionId": "{{promotionId}}"
}