POST /user/action?auth={{accessToken}}&action=rbs.partnerauth.request.LOGIN HTTP/1.1
Host: {{host}}

{
    "phoneNumber": "905314048097"
}

###

# @name validateLoginChallenge
POST /user/action?auth={{accessToken}}&action=rbs.partnerauth.request.ANSWER_CHALLENGE HTTP/1.1
Host: {{host}}

{
    "challengeId": "4514403f-ef61-4d1b-8df5-43a2f9af7ef3",    
    "challengeAnswer": "500170"
}