POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.LOGIN?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "phoneNumber": "905314048097"
}

###

# @name validateLoginChallenge
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "2fe3bada-57f1-405d-bc40-fcb0add89ee2",    
    "challengeAnswer": "141414"
}