
# @name register
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.REGISTER?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "phoneNumber": "905306129661"
}


###

# @name validatePhoneNumber
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "31275b78-b2ef-4dea-9630-ae8f38f81693",    
    "challengeAnswer": "542284"
}

###

# @name validatePartner
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "b976df3e-6c66-4541-88d6-da3eb3fae361",
    "verificationType": "INVITATION_CODE",
    "code": "118943",
    "phoneNumber": "905314048097",
    "email": "ahmet@mail.net",
    "userInformation": {
        "name": "Ahmet",
        "surname": "Deniz",
        "kvkk": true,
        "platform": "web"
    }
}

###

# @name validateEmail
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "967932f6-5704-4007-862e-b2c34af39e31",    
    "challengeAnswer": "136699"
}