
# @name register
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.REGISTER?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "phoneNumber": "905314048097"
}


###

# @name validatePhoneNumber
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "0f760be8-a5d1-49a3-aaf5-e0e004031834",    
    "challengeAnswer": "208260"
}

###

# @name validatePartner
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "f3c9aad9-4225-4b23-8569-0189835dfd77",
    "verificationType": "INVITATION_CODE",
    "phoneNumber": "905314048097",
    "code": "118943",
    "email": "ahmet@mail.net",
    "userInformation": {
        "name": "Ahmet",
        "surname": "Deniz",
        "kvkk": true,
        "platform": "web"
    }
}

###

# @name validateEmail
POST https://{{host}}/user/action/{{projectId}}/rbs.partnerauth.request.ANSWER_CHALLENGE?auth={{accessToken}} HTTP/1.1
Host: {{host}}

{
    "challengeId": "967932f6-5704-4007-862e-b2c34af39e31",    
    "challengeAnswer": "136699"
}