

# Delete item
POST https://{{host}}/service/action/{{projectId}}/rbs.catalog.request.DELETE_ITEM?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "id": "sku1112",
    "variantGroupId": "sku1112",
    "modelName": "rbs.pimproduct"
}