POST /user/action?auth={{accessToken}}&action=rbs.pimproduct.request.SET_CONFIG HTTP/1.1
Host: {{host}}

{
  "locales": [
    "en_US",
    "tr_TR"
  ],
  "resizeConfigs": [
    {
      "width": 1024,
      "guid": "web",
      "height": 1024,
      "quality": 90
    },
    {
      "width": 200,
      "guid": "mobile",
      "height": 200,
      "quality": 90
    }
  ]
}
    
