POST https://{{host}}/user/action/{{projectId}}/rbs.pimproduct.request.SET_CONFIG?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
  "locales": [
    "en_US",
    "tr_TR"
  ],
  "resizeConfigs": [
    {
      "width": 1024,
      "guid": "web",
      "height": 1024,
      "quality": 90
    },
    {
      "width": 200,
      "guid": "mobile",
      "height": 200,
      "quality": 90
    }
  ]
}
    
