POST /user/action?auth={{accessToken}}&action=rbs.pimproduct.request.UPSERT_PRODUCT HTTP/1.1
Host: {{host}}

{
  "sku": "7690",
  "isParent": false,
  "isSearchable": false,
  "variantGroupId": "D",
  "categories": [
    "Soslar"
  ],
  "attributes": [
      {
        "attributeId": "size",
        "variantValue": "xtiny"
      }
    ]
}