POST https://{{host}}/user/action/{{projectId}}/rbs.pimproduct.request.UPSERT_PRODUCT?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
  "sku": "7690",
  "isParent": false,
  "isSearchable": false,
  "variantGroupId": "D",
  "categories": [
    "Soslar"
  ],
  "attributes": [
      {
        "attributeId": "size",
        "variantValue": "xtiny"
      }
    ]
}