POST https://{{host}}/user/action/{{projectId}}/rbs.pimproduct.request.UPSERT_CATEGORY?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "id":"dondurulmusurun",
    "parentId":"B2C",
    "name":[{"locale":"en_US","value":"Dondurulmuş Ürünler"},{"locale":"tr_TR","value":"Dondurulmuş Ürünler"}],
    "image":
        {
            "contentEncoding":"base64",
            "alias":"iStock_000016966331_Medium.jpg",
            "resizeConfigs":[
                {"width":1024,"guid":"1609275600000-web","height":1024,"quality":90},
                {"width":200,"guid":"1609275600000-mob","height":200,"quality":90}
            ],
            "contentType":"image/jpeg"
        }
    
}