POST /user/action?auth={{accessToken}}&action=rbs.pimproduct.request.UPSERT_ATTRIBUTE HTTP/1.1
Host: {{host}}


{
    "id": "baranNumberAttribute",
    "attributeType": "number",
    "isLocalized": false,
    "isMandatory": false,
    "isListAttribute": false
    
}

# {
#     "id": "barantestattr2",
#     "attributeType": "boolean",
#     "isLocalized": false,
#     "isMandatory": false,
#     "isListAttribute": false
    
# }

# {
#     "id": "barantestattr",
#     "attributeType": "list",
#     "isLocalized": false,
#     "isMandatory": false,
#     "isListAttribute": false
    
# }