POST https://{{host}}/user/action/{{projectId}}/rbs.pimproduct.request.UPSERT_ATTRIBUTE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "id": "baranNumberAttribute",
    "attributeType": "number",
    "isLocalized": false,
    "isMandatory": false,
    "isListAttribute": false
    
}

# {
#     "id": "barantestattr2",
#     "attributeType": "boolean",
#     "isLocalized": false,
#     "isMandatory": false,
#     "isListAttribute": false
    
# }

# {
#     "id": "barantestattr",
#     "attributeType": "list",
#     "isLocalized": false,
#     "isMandatory": false,
#     "isListAttribute": false
    
# }