###
# @name createTrackingNumber
POST https://{{host}}/user/action/{{projectId}}/rbs.trackingnumber.request.CREATE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "cargoCompany": "ARASKARGO",
    "orderId": "88887",
    "alias": "alias",
    "receiverInformation": {
        "nameSurname": "Ahmet Deniz",
        "phoneNumber": "905314048097",
        "email": "ahmet@rettermobile.com",
        "address": "Zühtüpaşa mahallesi 2.hat boyu sokak no:5 daire: 9",
        "city": "İstanbul",
        "district": "Kadıköy",
        "customerReferenceType": "Unilever Turkiye"
    }
}

###
# @name getTrackingNumber
POST https://{{host}}/user/action/{{projectId}}/rbs.trackingnumber.request.GET?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "orderId": "070eb076e9f9472d8515b002c7bb3982#shipment#test50"
}

###
# @name cancelTrackingNumber
POST https://{{host}}/user/action/{{projectId}}/rbs.trackingnumber.request.CANCEL?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "orderId": "90532313"
}