# @name createCard

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.CREATE?auth={{accessToken}} HTTP/1.1

###

@cartId = {{createCard.response.body.$[0].response.cartId}}

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.ADD_ITEM?auth={{accessToken}} HTTP/1.1

{
    "itemId": "152902238",
    "variantGroupId": "karisikpizza",
    "merchantId": "default",
    "qty": 3
}
###
POST {{host}}/user/action/{{projectId}}/rbs.cart.request.REMOVE_ITEM?auth={{accessToken}} HTTP/1.1

{
    "merchantId": "default",
    "variantGroupId": "D",
    "itemId": "768521",
    "qty": 4
}
###

# @name getCart

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.GET?auth={{accessToken}} HTTP/1.1

{
    "serviceFee": 15
}
###

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.SUMMARY?auth={{accessToken}} HTTP/1.1

{
    "serviceFee": 15
}
