# @name createCard

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.CREATE?auth={{accessToken}} HTTP/1.1

###

@cartId = {{createCard.response.body.$[0].response.cartId}}

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.ADD_ITEM?auth={{accessToken}} HTTP/1.1

{
    "itemId": "153100000",
    "variantGroupId": "tamyaglisut",
    "merchantId": "pınarMerchant",
    "qty": 3
}
###
POST {{host}}/user/action/{{projectId}}/rbs.cart.request.REMOVE_ITEM?auth={{accessToken}} HTTP/1.1

{
    "itemId": "153100000",
    "variantGroupId": "tamyaglisut",
    "merchantId": "pınarMerchant",
    "qty": 1
}
###

# @name getCart

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.GET?auth={{accessToken}} HTTP/1.1

{
    "serviceFee": 15,
    "zoneId": "zoneA"
}
###

POST {{host}}/user/action/{{projectId}}/rbs.cart.request.SUMMARY?auth={{accessToken}} HTTP/1.1

{
    "serviceFee": 15,
    "zoneId": "zoneA"
}
