POST /user/action?auth={{accessToken}}&action=rbs.cms.request.UPSERT_TEMPLATE HTTP/1.1
Host: {{host}}

{
    "id": "D2BD74C2-7650-4A88-B572-7F13537A17FE",
    "name": "Yemek Tarifi",
    "templateItem": {
        "id": "D2BD74C2-7650-4A88-B572-7F13537A17FE",
        "itemType": "someType",
        "name": "something1",
        "attributes": [{
            "itemType": "size",
            "value"
        }],
        "children": []
    }
}


