POST /user/action?auth={{accessToken}}&action=rbs.cms.request.UPSERT_CONTENT HTTP/1.1
Host: {{host}}

{
	"id": "47c7927e-d04a-42a0-a0f4-301a28ec37f7",
	"name": "ozgur hellooo",
	"itemType": "Yemek Tarifi Ozgur",
	"attributes": [
		
	],
	"parentId": "19128631-6ed1-4190-a610-d8511f3b3c18",
	"children": []
}