###
### // numbers (0123456789), alphabetic (abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ) // alphanumeric (0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ)
# @name createCode
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.CREATE_CODE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "type": "PARTNER_KEY_CODE",
    "groupId": "çanta",
    "count": 100,
    "length": 10,
    "charset": "numbers",
    "prefix": "",
    "postfix": ""
}

###
# @name createCode
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.CREATE_CODE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "type": "STATIC_CODE",
    "groupId": "turkcell",
    "code": "MAVI",
    "partner": "mavi",
    "usableCount": 5000
}

###
# @name createCode
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.CREATE_CODE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "type": "FRIENDS_FAMILY_CODE",
    "invitedBy": "davet eden numara",
    "invitedPhoneNumber": "davet edilen numara"
}

###

# @name getGroups
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.GET_GROUPS?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{}

###

# @name getCode
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.GET_CODE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "code": "188007859943"
}

###

# @name markAsUsed
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.MARK_AS_USED?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "code": "188007859943",
    "userId": "123123"
}

###

# @name exportExcel
POST https://{{host}}/user/action/{{projectId}}/rbs.codegenerator.request.EXPORT_EXCEL?auth={{accessToken}} HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
    "groupId": "mess"
}