
POST https://{{host}}/user/action/{{projectId}}/rbs.catalog.request.Add_TAG?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "modelName": "rbs.pimproduct",
    "catalogItemId": "1234",
    "tags": "test2,test3,zone#ankara"
}