POST https://{{host}}/user/action/{{projectId}}/rbs.catalog.request.SEARCH?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "from": 0,
    "size": 100,
    "searchTerm": "pizza",
    "filters": [
        
    ]
}