POST https://{{host}}/user/action/{{projectId}}/rbs.logistics.request.GET_POOLS?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "cart": {
        "cartId": "TEST",
        "items": [
            {
                "merchantId": "AliMerchant",
                "variantGroupId": "AliVaraiantGroupId",
                "itemId": "AliItemId"
            }
        ]
    },
    "address": {
        "addressId": "01EYMX24JNP5439ND40RWM3GPS",
        "name": "Test Address",
        "country": "TÜRKİYE",
        "city": "İSTANBUL",
        "district": "ATAŞEHİR"
    },
    "zoneId": "zoneA"
}