POST https://{{host}}/user/action/{{projectId}}/rbs.logistics.request.UPSERT_OPTION?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "optionId": "SHIPMENT",
    "data": {
        "days": 3,
        "linearStatuses": true
    }
}