POST https://{{host}}/user/action/{{projectId}}/rbs.logistics.request.UPSERT_OPTION?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "optionId": "SHIPMENT_STATUSES",
    "data": [
            { "status": "CANCELLED", "cancel": true },
            { "status": "PENDING", "cancellable": true, "addable": true },
            { "status": "PACKAGING", "addable": true, "back": true },
            { "status": "READY", "back": true },
            { "status": "IN_TRANSIT", "trackDelivery": true },
            { "status": "DELIVERED", "triggerInvoice": true }
        ]
}