POST https://{{host}}/user/action?auth={{accessToken}}&action=rbs.logistics.request.UPSERT_SHIPMENT_PROVIDER HTTP/1.1
Content-Type: application/json

{
    "merchantId": "DEFAULT",
    "storeId": "STORE_A",
    "shipmentType": "CARGO",
    "providerId": "YURTICI_KARGO",
    "name": "Yurtiçi Kargo",
    "data": {}
}
