POST https://{{host}}/user/action/{{projectId}}/rbs.logistics.request.UPSERT_SHIPMENT_PROVIDER?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "merchantId": "DEFAULT",
    "storeId": "STORE_A",
    "shipmentType": "CARGO",
    "providerId": "YURTICI_KARGO",
    "name": "Yurtiçi Kargo",
    "data": {}
}
