POST https://{{host}}/user/action/{{projectId}}/rbs.logistics.request.UPSERT_ZONE?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "zoneId": "TEST_ZONE",
    "name": "Test Zone",
    "rules": [
        {
            "addr": {
                "city": {
                    "IN": [
                        "NEW YORK"
                    ]
                }
            }
        }
    ]
}