
POST https://{{host}}/user/action/{{projectId}}/rbs.address.request.UPSERT_ADDRESS?auth={{accessToken}} HTTP/1.1
Content-Type: application/json

{
    "name": "Test Address",
    "country": "TÜRKİYE",
    "city": "İSTANBUL",
    "district": "ATAŞEHİR"
}